spring.application.name=S3-Project
spring.datasource.url=jdbc:postgresql://localhost:5332/s3project
spring.datasource.username=aeon
spring.datasource.password=aeon
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


